### PR TITLE
Implements SetupDapperAsync for IDbConnection.

### PR DESCRIPTION
**Pull request by LTMenezes**
This pull request implements SetupDapperAsync for IDbConnection, previously we could only test Dapper async methods mocking a DbConnection.

I look forward for your feedback on this.

### CODE REVIEW

**Comment by UnoSD** [comment]
Thanks for the PR @LTMenezes, I had a really quick glance (hopefully I will have time this weekend to merge it).

One comment is that Execute*Async is not part of the interfaces, one safeguard could be to check if the current implementation of IDb* is a Db* class or check the existence of the method before invoking `Protected.Setup`. I will be happy to add it myself when I get a chance though.

**Comment by LTMenezes** [comment]
@UnoSD I`m really glad you liked it.

I agree we must have this extra check inside the SetupDapperAsync since ExecuteAsync is not part of the interfaces.

I`m a bit busy at the moment, so I will probably only have time to look at this next week. If you haven`t implemented this until then I`m glad to implement this myself.

**Comment by UnoSD** [comment]
@LTMenezes great spot for the:

```
iDbConnectionMock.SetupGet(m => m.State)
                             .Returns(ConnectionState.Open);
```

I've moved the fix of the typo in a separate commit and extracted the common logic to other classes. All looks good, merging in. Thank you for your contribution.

**Comment by LTMenezes** [comment]
@UnoSD Awesome, congratulations for this great project, I look forward to contributing in the future.

**Pull request merged**
