### PR TITLE
Add support for Single, SingleOrDefault, First and FirstOrDefault

### PR DESCRIPTION
**Pull request by oppewala**
I've added a support for the Single, SingleOrDefault, First and FirstOrDefault queries.

I haven't been able to get 'ThrowsException' working, as the way the DbCommandSetup stuff works means that it throws the exception when the SetupCommand method is called, not when the mock is actually invoked.

### CODE REVIEW

**Comment by oppewala** [comment]
I've updated the code to reflect the preferred indentation style (and updated the resharper config to do it automatically). 

The GetAwaiter().GetResult() should potentially be a separate pull request, since it's not related to adding Single/SingleOrDefault/First/FirstOrDefault.

**Comment by UnoSD** [comment]
Thank you for that. I will probably have some time only in January to look at it, but I will do my best to do it sooner. Can you please remove refactoring that is not related to the change?

**Comment by oppewala** [comment]
Hi @UnoSD, I've undone what I think you meant by unrelated refactoring. Let me know if you think I've missed something.

**Comment by jerone** [comment]
@UnoSD Can this be merged? We need these methods in our tests.

**Comment by electroholic** [comment]
@UnoSD Hi - can I second the vote to get this merged into master and published on nuget please?

**Comment by imad-mn** [comment]
Hello @UnoSD , can you please merge this into master and get it published?  I believe many people is waiting for this change.

**Comment by Lonli-Lokli** [comment]
@imad-mn you can try my fork, https://www.nuget.org/packages/Dapper.Moq/

**Pull request merged**
